apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "helper.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "helper.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ include "helper.name" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helper.name" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    spec:
    {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: {{ include "helper.name" . }}-env
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- with .Values.pod_securityContext }}
        securityContext:
{{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /data/
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "helper.name" . }}-config

