apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "sn.fullname" . }}"
data:
  DEBUG: {{ .Values.DEBUG | upper | quote }}
  ALLOWED_HOSTS: {{ .Values.ALLOWED_HOSTS | quote }}
  CSRF_COOKIE_SECURE: {{ .Values.CSRF_COOKIE_SECURE | upper | quote }}
  SESSION_COOKIE_SECURE: {{ .Values.SESSION_COOKIE_SECURE | upper | quote }}
  DB_ENGINE: {{ .Values.db.engine }}
  DB_HOST: {{ .Values.db.host }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name }}
  BLACKLIST_ENABLE: {{ .Values.blacklist.enabled | upper | quote }}
  BLACKLIST_RELOAD_PERIOD: {{ .Values.blacklist.reload_period | quote }}
