{{- if .Values.external_secret.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ template "sn.fullname" . }}"
spec:
  backendType: secretsManager
  data:
  - key: {{ .Values.external_secret.app_secrets }}
    name: SECRET_KEY
    property: SECRET_KEY
  - key: {{ .Values.external_secret.db}}
    name: DB_PASSWORD
    property: MasterPassword
  - key: {{ .Values.external_secret.db}}
    name: DB_USER
    property: MasterUsername
  - key: {{ .Values.external_secret.app_secrets }}
    name: DEFAULT_KEY
    property: DEFAULT_KEY
{{- end }}