apiVersion: v1
kind: Service
metadata:
  name: {{ include "sn.fullname" . }}
  labels:
{{ include "sn.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sn.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
